server:
  port: 8080
#  spring.main.web-application-type:reactive

spring:
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:mysql://localhost:3306/ms_db
    username: abir
    password: 3323
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  cloud:
    gateway: 
      routes:
        - id: INFORMATION-SERVICE
          uri: lb://INFORMATION-SERVICE
          predicates: 
          - Path=/info/**
          filters:
            - name: CircuitBreaker
              args:
                name: INFORMATION-SERVICE
                fallbackuri: forward:/info-service-fallback
        - id: NEWSFEED-SERVICE
          uri: lb://NEWSFEED-SERVICE
          predicates: 
          - Path=/feed/**
          filters:
            - name: CircuitBreaker
              args:
                name: NEWSFEED-SERVICE
                fallbackuri: forward:/feed-service-fallback
            - name: CustomFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates: 
          - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/user-service-fallback
            - name: CustomFilter
  application: 
    name: GATEWAY-SERVICE

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

    
    
    